//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int id { get; set; }
        public string nombre_c { get; set; }
        public string apellido_c { get; set; }
        public string telefono_c { get; set; }
        public string dni_c { get; set; }
        public System.DateTime fechaAlta_dt { get; set; }
        public System.DateTime fechaBaja_dt { get; set; }
        public bool sexo_b { get; set; }
    }
}
