//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_modulos_permisos
    {
        public int id { get; set; }
        public int modulo_x { get; set; }
        public Nullable<int> usuario_x { get; set; }
        public System.DateTime fecha_ini { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public int grupo_x { get; set; }
    
        public virtual erp_grupos erp_grupos { get; set; }
        public virtual erp_modulos erp_modulos { get; set; }
    }
}
