//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_funciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public erp_funciones()
        {
            this.erp_funciones1 = new HashSet<erp_funciones>();
            this.erp_funciones_permisos = new HashSet<erp_funciones_permisos>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string icono_small { get; set; }
        public string icono_big { get; set; }
        public string url { get; set; }
        public bool activo { get; set; }
        public bool menu { get; set; }
        public int modulo_x { get; set; }
        public Nullable<int> funcion_x { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_funciones> erp_funciones1 { get; set; }
        public virtual erp_funciones erp_funciones2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_funciones_permisos> erp_funciones_permisos { get; set; }
    }
}
