//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public erp_pedidos()
        {
            this.erp_pedidos_item = new HashSet<erp_pedidos_item>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public string estado { get; set; }
        public int cliente_x { get; set; }
    
        public virtual erp_clientes erp_clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_pedidos_item> erp_pedidos_item { get; set; }
    }
}
