//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_productos_ofertas
    {
        public int id { get; set; }
        public int producto_x { get; set; }
        public int oferta_x { get; set; }
        public System.DateTime fecha_ini { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
    
        public virtual erp_ofertas erp_ofertas { get; set; }
        public virtual erp_productos erp_productos { get; set; }
    }
}
