//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_pedidos_item
    {
        public int id { get; set; }
        public int pedido_x { get; set; }
        public int cantidad { get; set; }
        public decimal total_bruto { get; set; }
        public decimal total_descuento { get; set; }
        public int producto_x { get; set; }
    
        public virtual erp_pedidos erp_pedidos { get; set; }
        public virtual erp_productos erp_productos { get; set; }
    }
}
