//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class taller_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public taller_cliente()
        {
            this.taller_vehiculo = new HashSet<taller_vehiculo>();
        }
    
        public int id { get; set; }
        public string dni_c { get; set; }
        public string nombre_c { get; set; }
        public string apellido1_c { get; set; }
        public string apelllido2_c { get; set; }
        public string telefono_c { get; set; }
        public string direccion_c { get; set; }
        public string localidad_c { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taller_vehiculo> taller_vehiculo { get; set; }
    }
}
